### ISSUE TITLE
Seeking Guidance for AVSR Project

### ISSUE THREAD

**Issue by yarragotiravitheja** [ShokSmile/Pubmed-Web-Application#1]
Hi Aleksandr Tarasov, 

I hope this message finds you well. I recently came across your Lip-Reader repository, and I'm impressed by your work on audio-visual speech recognition (AVSR). As I'm working on a similar project, I would greatly appreciate any guidance or insights you can provide.

I apologize for reaching out through an issue, but I couldn't find any other contact information. If there's a more suitable way to connect, please let me know.

Thank you for your time, and I look forward to hearing from you.

Best regards,
Ravi Theja

**Comment by ShokSmile** [comment]
Hello Ravi Theja! 

Actually and I've written this in the readme that AVSR is META's project. I've only forked it. You can find all the docs in main branch of their project. 

Have a nice day!

**Comment by yarragotiravitheja** [comment]
Got it, thank you for ur quick response.
